language: python

python:
  - 2.7
  - 3.4


before_install:

  # Use utf8 encoding. Should be default, but this is insurance against
  # future changes
  - export PYTHONIOENCODING=UTF8
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda


install:
  - conda create --yes -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda update --yes conda
  - source activate test-environment
  # Useful for debugging any issues with conda
  - conda info -a

  - conda install --yes pip
  - conda install --yes six
  - conda install --yes ipython-notebook
  - conda install --yes numpy
  - conda install --yes scipy
  - conda install --yes pandas
  - conda install --yes matplotlib
  - conda install --yes pytest
  - conda list
  - python setup.py install

script:
    - py.test --runslow pambox/tests
